/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Terminkalender.GUIPart;

import Terminkalender.BenutzerException;
import Terminkalender.Datum;
import Terminkalender.LauncherInterface;
import Terminkalender.TerminException;
import Terminkalender.Zeit;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author niroshan
 */
public class Fenster extends javax.swing.JFrame {

    private final LauncherInterface stub;

    /**
     * Creates new form Fenster
     *
     * @param stub
     */
    public Fenster(LauncherInterface stub) {
        initComponents();
        this.stub = stub;
    }

    private Fenster() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    public void zuweisen(String username, String password) throws RemoteException, BenutzerException, TerminException, Datum.DatumException, Zeit.ZeitException {

        if (stub.einloggen(username, password)) {
            Hauptfenster start = new Hauptfenster(stub);
            start.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "Anmelden gescheitert!", "anmelden", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBenutzername = new javax.swing.JLabel();
        jPasswort = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBenutzernameField = new javax.swing.JTextField();
        jAnmelden = new javax.swing.JButton();
        jRegistrieren = new javax.swing.JButton();
        jBeenden = new javax.swing.JButton();
        jPasswortField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBenutzername.setText("Benutzername");

        jPasswort.setText("Passwort");

        jLabel3.setText("jLabel3");

        jAnmelden.setText("Anmelden");
        jAnmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnmeldenActionPerformed(evt);
            }
        });

        jRegistrieren.setText("Registrieren");
        jRegistrieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistrierenActionPerformed(evt);
            }
        });

        jBeenden.setText("Beenden");
        jBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeendenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jAnmelden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRegistrieren)
                        .addGap(18, 18, 18)
                        .addComponent(jBeenden))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPasswort)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswortField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBenutzername)
                                .addGap(49, 49, 49)
                                .addComponent(jBenutzernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBenutzername)
                    .addComponent(jBenutzernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswort)
                    .addComponent(jPasswortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnmelden)
                    .addComponent(jRegistrieren)
                    .addComponent(jBeenden))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAnmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnmeldenActionPerformed
        // TODO add your handling code here:
        String username, password;

        username = this.jBenutzernameField.getText();

        password = this.jPasswortField.getText();

        try {
            this.zuweisen(username, password);
        } catch (RemoteException e) {
            JOptionPane.showInputDialog(e.getMessage());
        } catch (BenutzerException e) {
            JOptionPane.showInputDialog(e.getMessage());
        } catch (TerminException e) {
            JOptionPane.showInputDialog(e.getMessage());
        } catch (Datum.DatumException e) {
            JOptionPane.showInputDialog(e.getMessage());
        } catch (Zeit.ZeitException e) {
            JOptionPane.showInputDialog(e.getMessage());
        }
    }//GEN-LAST:event_jAnmeldenActionPerformed

    private void jRegistrierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistrierenActionPerformed
        // TODO add your handling code here:
        Registrieren start = new Registrieren(stub);
        start.setVisible(true);
    }//GEN-LAST:event_jRegistrierenActionPerformed

    private void jBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeendenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBeendenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAnmelden;
    private javax.swing.JButton jBeenden;
    private javax.swing.JLabel jBenutzername;
    private javax.swing.JTextField jBenutzernameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jPasswort;
    private javax.swing.JPasswordField jPasswortField;
    private javax.swing.JButton jRegistrieren;
    // End of variables declaration//GEN-END:variables
}
